Neos:
  ContentRepositoryRegistry:
    presets:
      'default':
        debug:
          tracer:
            factoryObjectName: Sandstorm\Plumber\Core\ContentRepository\ContentRepositoryPlumberTracerFactory
